#logging:
#  config: classpath:logback-sit.xml

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HANAColumnStoreDialect
        jdbc:
          lob:
            non_contextual_creation: true