logging:
  config: classpath:logback-dev.xml

##web容器配置
server:
  port: 8080
  servlet:
    context-path: /portal-api

spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: biao.chenit@qq.com #QQ邮箱
    password: atlvzzlyladkbgaf #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致

  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/yg-portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

coresuite:
  api:
    token-root-url: https://auth.coresuite.com/api
    call-root-url: https://cn.coresuite.cn/api
    root-local: ${coresuite.api.root-url}/oauth2/v1/token
  authorization: Basic MTIzZDAxZWQtZTExNy00YWRlLWFmYzQtN2U2OTdhYTQ1OTRmOjZjZmZmZGM1LTdlMjktNGM4YS1iNTRkLTEyZjgyMzI5ZTdmNg==
  grant_type: password
  username: sungrowpower-p1/dev
  password: Welcome2020
  mimeType: application/x-www-form-urlencoded
  auth:
    username: S0020469033
    password: CRM@Unisoc

ftp:
  host: 10.29.24.20
  port: 21
  username: crmftp
  password: '123@qwe'
  path:
    handover:
      push: /handover/push/
      pull: /handover/pull/
    forecast:
      push: /bitest/upload/
      pull: /bitest/download/
