logging:
  config: classpath:logback-dev.xml

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
  h2:
    console:
      enabled: true
coresuite:
  api:
    token-root-url: https://auth.coresuite.com/api
    call-root-url: https://cn.coresuite.cn/api
    root-local: ${coresuite.api.root-url}/oauth2/v1/token
  authorization: Basic MTIzZDAxZWQtZTExNy00YWRlLWFmYzQtN2U2OTdhYTQ1OTRmOjZjZmZmZGM1LTdlMjktNGM4YS1iNTRkLTEyZjgyMzI5ZTdmNg==
  grant_type: password
  username: sungrowpower-p1/dev
  password: Welcome2020
  mimeType: application/x-www-form-urlencoded
  auth:
    username: S0020469033
    password: CRM@Unisoc
