logging:
  config: classpath:logback-sit.xml

##web容器配置
server:
  port: 8080
  servlet:
    context-path: /portal-api

app:
  ad-domain: THREEAPE.CN
  service-principal: HTTP/tomcat.threeape.cn@THREEAPE.CN
  keytab-location: /Users/Bill/Desktop/tomcat.keytab
  krb5-config: /Users/Bill/Desktop/krb5.ini

spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: biao.chenit@qq.com #QQ邮箱
    password: atlvzzlyladkbgaf #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致

  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

file:
  path:
    root: /service/ftp/portal_file #公用基础路径
    root-local: ${file.path.root}/local #portal系统内文件地址入口
    root-thrid-push: ${file.path.root}/push_thrid #portal对接第三方文件出口地址
    root-thrid-pull: ${file.path.root}/pull_thrid #第三方传输文件至portal入口地址
    root-template: ${file.path.root}/template #portal功能模版文件地址
    customer: ${file.path.root-local}/customer/
    reader-customer: ${portal.file-url}/local/customer/
    reader-dir: ${portal.file-url}/business/
    announcement: #公告管理模块
      local: ${file.path.root-local}/announcement/
    deliver: #出货管理模块
      template: ${file.path.root-template}/deliver/
      push: ${file.path.root-thrid-push}/deliver/
      pull: ${file.path.root-thrid-pull}/deliver/
      local: ${file.path.root-local}/deliver/
    receive: #收货管理模块
      template: ${file.path.root-template}/receive/
      push: ${file.path.root-thrid-push}/receive/
      pull: ${file.path.root-thrid-pull}/receive/
      local: ${file.path.root-local}/receive/
    forecast:
      push: ${file.path.root-thrid-push}/forecast/
      pull: ${file.path.root-thrid-pull}/forecast/

portal:
  view-url: http://portal-sit.threeape.cn/portal/#/pwd
  file-url: http://portal-sit.threeape.cn/portal-api/file
  mock-bi-server: on

ecc:
  api:
    url: https://e600180-hcioem.hcisbt.cn1.hana.ondemand.com
  auth:
    username: S0020469033
    password: CRM@Unisoc
ftp:
  host:
  port:
  username:
  password:
  path:
    handover:
      push: /handover/push/
      pull: /handover/pull/
    forecast:
      push: /bitest/upload/
      pull: /bitest/download/