##web容器配置
server:
  port: 1024
  servlet:
    context-path: /sun-portal-api
spring:
  profiles:
    active: dev
  messages:
    basename: static/i18n/messages
  ##thymelef配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  ##文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB