logging:
  config: classpath:logback-sit.xml

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HANAColumnStoreDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: biao.chenit@qq.com #QQ邮箱
    password: atlvzzlyladkbgaf #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致

hana:
  url: jdbc:sap://hana-a62-factorycn1-flk6l92j.sha3.od.sap.biz:30015/
  user: S0017474203
  password: Portal201912345

coresuite:
  api:
    token-root-url: https://auth.coresuite.com/api
    call-root-url: https://cn.coresuite.cn/api
    root-local: ${coresuite.api.root-url}/oauth2/v1/token
  authorization: Basic MTIzZDAxZWQtZTExNy00YWRlLWFmYzQtN2U2OTdhYTQ1OTRmOjZjZmZmZGM1LTdlMjktNGM4YS1iNTRkLTEyZjgyMzI5ZTdmNg==
  grant_type: password
  username: sungrowpower-p1/dev
  password: Welcome2020
  mimeType: application/x-www-form-urlencoded
  auth:
    username: S0020469033
    password: CRM@Unisoc
