##web容器配置
server:
  port: 1024
  servlet:
    context-path: /sun-portal
spring:
  profiles:
    active: @activatedProperties@
  messages:
    basename: static/i18n/messages
  ##文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB